name: formulearn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase (todas compatibles entre sí)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3     # <- ACTUALIZADO (compatible con core ^4 y auth ^6)

  # Selección de archivos (PDF/imagenes/etc)
  file_picker: ^8.0.3

  # IA / ML / utilidades
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.1.1
  google_mlkit_text_recognition: ^0.15.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  http: ^1.2.2
  lottie: ^3.3.2
  keyboard_actions: ^4.2.0
  flutter_math_fork: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/form.json
